### ISSUE TITLE
CryGameSDK build error after add Plugin_SDK

### ISSUE THREAD

**Issue by guoning1002** [hendrikp/Plugin_SDK#22]
Error info:
Error	90	error C2259: 'CFactory<AnimPoseModifier::CLookAtSimple>' : cannot instantiate abstract class (Game.cpp)	c:\cryengine\code\cryengine\cryaction\animation\posemodifier\lookatsimple.h	25	1	CryGameSDK
Error	91	error C2259: 'CFactory<CIKTorsoAim>' : cannot instantiate abstract class (Game.cpp)	c:\cryengine\code\cryengine\cryaction\animation\posemodifier\iktorsoaim.h	16	1	CryGameSDK

Notes:
I follow the GameDLL Integration guide

Windows8, 
VS professional 2013
CRYENGINE_Build_PC_v3_5_8_2310_freesdk.zip
Plugin_SDK.git

**Comment by SalahAdDin** [comment]
:+1:

**Comment by hendrikp** [comment]
Use the version that was released for this old FreeSDK version (lookup in
changelog and download the appropriatly tagged version)

2015-09-01 3:20 GMT+02:00 Yusuf (Josè) Luis <notifications@github.com>:

**Comment by guoning1002** [comment]
Hi hendrikp:
     So where can i find the match version, on cryengine office i only can download CRYENGINE_Build_PC_v3_5_8_2310_freesdk.zip version, is there any place i can download old version free for my study?

**Comment by hendrikp** [comment]
Hi,

Plugin SDK 2.0.0 (29.11.2013)

Stable Release for CryEngine 3.5.4 (32/64 bit)

This is the closest version to 3.5.8, the errors you will need to fix
yourself. (Mostly its always simply macro stuff that changed a bit)

See: https://github.com/hendrikp/Plugin_SDK/releases

2015-09-02 6:44 GMT+02:00 guoning1002 <notifications@github.com>:
