### ISSUE TITLE
Cryengine 5 Compatibility? 

### ISSUE THREAD

**Issue by benoneal** [hendrikp/Plugin_SDK#25]
I just downloaded the installer and ran it, then confirmed that everything was installed in the correct locations by going through the manual installation steps in the wiki, including confirming that the VSZ file pointed to the correct location of the install. However when I open my project, none of the cvars are available: ```pm_list is not Editor command or a cvar```, leading me to believe I've missed something? Also will it work with VS2015?

**Comment by hendrikp** [comment]
yes vs2015 is no problem, have a look at this already migrated version https://github.com/omggomb/Plugin_SDK this one seems to be ported to CEV.
