### ISSUE TITLE
 please updata plugin_sdk for Amazon Lumberyard ,Thank you hendrikp!

### ISSUE THREAD

**Issue by dingwangfan** [hendrikp/Plugin_SDK#29]
please updata plugin_sdk for Amazon Lumberyard ,Thank you hendrikp!

**Comment by hendrikp** [comment]
lumberyard has gems, no need for plugins there.

2016-06-03 17:36 GMT+02:00 dingwangfan notifications@github.com:

**Comment by dingwangfan** [comment]
I want to add Plugin_Shroud for lumberyard,but can't  found the right way,please help me,Thanks!
